# Generated by Django 4.1.3 on 2023-01-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DISCLOSURE',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_by', models.CharField(max_length=254)),
                ('Nature_of_UPSI', models.CharField(max_length=254)),
                ('Purpose_of_sharing', models.CharField(max_length=254)),
                ('Remark', models.CharField(max_length=254)),
                ('shared_on', models.DateField()),
                ('disc_Attachment', models.FileField(upload_to='')),
                ('Recipients_name', models.CharField(max_length=100)),
                ('Recipients_email', models.EmailField(max_length=100)),
                ('Recipients_mobile_number', models.CharField(max_length=18)),
                ('Recipients_Id_Type', models.CharField(max_length=100)),
                ('Recipients_Id_Number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DISCLOSURE',
            },
        ),
        migrations.CreateModel(
            name='UPSI',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nature', models.CharField(max_length=254, null=True)),
                ('Purpose', models.CharField(max_length=254, null=True)),
                ('Remark', models.CharField(max_length=500, null=True)),
                ('Attachment1', models.FileField(upload_to='')),
                ('Attachment2', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'UPSI',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
