# Generated by Django 4.1.3 on 2023-01-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSD_APP', '0002_alter_disclosure_nature_of_upsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='shared_by',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
