# Generated by Django 4.1.3 on 2023-01-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSD_APP', '0004_alter_disclosure_nature_of_upsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='Recipients_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
